import type { CategoryBehaviorProfile, ResellerBehaviorProfile } from "./types";

export const CATEGORY_BEHAVIOR_MATRIX: Record<ResellerBehaviorProfile, CategoryBehaviorProfile> = {
  COLLECTIBLE: {
    profile: "COLLECTIBLE",
    minTrustedSolds: 2,
    minConfidenceForBuy: 62,
    maxSaturationRatio: 6,
    minSellThroughRate: null,
    minRoiForBuy: 30,
    minNetProfitForBuy: 8,
    staleCompToleranceDays: 365,
    requiresBundleValidation: false,
    requiresStrictUpc: false,
    shippingTolerance: "MEDIUM",
    longTailAllowed: true
  },
  LONG_TAIL_VINTAGE: {
    profile: "LONG_TAIL_VINTAGE",
    minTrustedSolds: 2,
    minConfidenceForBuy: 60,
    maxSaturationRatio: 5,
    minSellThroughRate: null,
    minRoiForBuy: 35,
    minNetProfitForBuy: 10,
    staleCompToleranceDays: 540,
    requiresBundleValidation: false,
    requiresStrictUpc: false,
    shippingTolerance: "MEDIUM",
    longTailAllowed: true
  },
  CONSUMABLE: {
    profile: "CONSUMABLE",
    minTrustedSolds: 6,
    minConfidenceForBuy: 82,
    maxSaturationRatio: 2,
    minSellThroughRate: 0.35,
    minRoiForBuy: 75,
    minNetProfitForBuy: 10,
    staleCompToleranceDays: 60,
    requiresBundleValidation: true,
    requiresStrictUpc: true,
    shippingTolerance: "LOW",
    longTailAllowed: false
  },
  BEAUTY: {
    profile: "BEAUTY",
    minTrustedSolds: 5,
    minConfidenceForBuy: 78,
    maxSaturationRatio: 2.5,
    minSellThroughRate: 0.3,
    minRoiForBuy: 65,
    minNetProfitForBuy: 9,
    staleCompToleranceDays: 90,
    requiresBundleValidation: true,
    requiresStrictUpc: true,
    shippingTolerance: "LOW",
    longTailAllowed: false
  },
  GROCERY: {
    profile: "GROCERY",
    minTrustedSolds: 6,
    minConfidenceForBuy: 84,
    maxSaturationRatio: 2,
    minSellThroughRate: 0.4,
    minRoiForBuy: 80,
    minNetProfitForBuy: 10,
    staleCompToleranceDays: 45,
    requiresBundleValidation: true,
    requiresStrictUpc: true,
    shippingTolerance: "LOW",
    longTailAllowed: false
  },
  TOYS: {
    profile: "TOYS",
    minTrustedSolds: 4,
    minConfidenceForBuy: 70,
    maxSaturationRatio: 4,
    minSellThroughRate: 0.2,
    minRoiForBuy: 45,
    minNetProfitForBuy: 8,
    staleCompToleranceDays: 180,
    requiresBundleValidation: false,
    requiresStrictUpc: false,
    shippingTolerance: "MEDIUM",
    longTailAllowed: true
  },
  ELECTRONICS: {
    profile: "ELECTRONICS",
    minTrustedSolds: 5,
    minConfidenceForBuy: 78,
    maxSaturationRatio: 3,
    minSellThroughRate: 0.28,
    minRoiForBuy: 45,
    minNetProfitForBuy: 15,
    staleCompToleranceDays: 120,
    requiresBundleValidation: false,
    requiresStrictUpc: true,
    shippingTolerance: "MEDIUM",
    longTailAllowed: false
  },
  MEDIA: {
    profile: "MEDIA",
    minTrustedSolds: 4,
    minConfidenceForBuy: 72,
    maxSaturationRatio: 3,
    minSellThroughRate: 0.25,
    minRoiForBuy: 60,
    minNetProfitForBuy: 6,
    staleCompToleranceDays: 180,
    requiresBundleValidation: false,
    requiresStrictUpc: false,
    shippingTolerance: "LOW",
    longTailAllowed: true
  },
  AUTO_PARTS: {
    profile: "AUTO_PARTS",
    minTrustedSolds: 4,
    minConfidenceForBuy: 78,
    maxSaturationRatio: 3,
    minSellThroughRate: 0.2,
    minRoiForBuy: 55,
    minNetProfitForBuy: 15,
    staleCompToleranceDays: 180,
    requiresBundleValidation: false,
    requiresStrictUpc: false,
    shippingTolerance: "HIGH",
    longTailAllowed: true
  },
  HIGH_SATURATION_RETAIL: {
    profile: "HIGH_SATURATION_RETAIL",
    minTrustedSolds: 8,
    minConfidenceForBuy: 85,
    maxSaturationRatio: 1.5,
    minSellThroughRate: 0.45,
    minRoiForBuy: 80,
    minNetProfitForBuy: 15,
    staleCompToleranceDays: 45,
    requiresBundleValidation: true,
    requiresStrictUpc: true,
    shippingTolerance: "LOW",
    longTailAllowed: false
  }
};
