import type { NormalizedMarketFacts } from "./types";

const base: NormalizedMarketFacts = {
  title: "",
  brand: "",
  category: "",
  upc: "",
  sourceStoreType: "",
  costBasis: null,
  averageSoldPrice: null,
  netProfit: null,
  roi: null,
  trustedSoldCount: 0,
  soldCount90d: 0,
  activeCount: 0,
  activeListingCount: 0,
  soldListingCount: 0,
  sellThroughRate: null,
  sellThroughRatio: null,
  saturationRatio: null,
  confidenceScore: 0,
  titleMatchScore: 0,
  visualMatchScore: 0,
  compRejectionRate: 0,
  shippingOverhead: 5.75,
  estimatedWeightClass: "STANDARD",
  shippingComplexity: "LOW",
  fragileRisk: false,
  returnRisk: false,
  incompleteListingRisk: false,
  oversizedPenalty: 0,
  isBundleDependent: false,
  isMultipack: false,
  bulkCompDetected: false,
  isConsumable: false,
  isCollectible: false,
  raritySignal: false,
  latestCompAgeDays: null,
  staleCompRatio: 0
};

export const resellerEngineFixtures: Record<string, NormalizedMarketFacts> = {
  dollarTreeConsumable: {
    ...base,
    title: "Dollar Tree snack box",
    category: "grocery",
    sourceStoreType: "DOLLAR_TREE",
    costBasis: 1.25,
    averageSoldPrice: 14,
    netProfit: 1.1,
    roi: 88,
    trustedSoldCount: 2,
    activeCount: 80,
    activeListingCount: 80,
    soldListingCount: 2,
    sellThroughRate: 0.03,
    sellThroughRatio: 0.03,
    saturationRatio: 40,
    confidenceScore: 52,
    titleMatchScore: 0.42,
    isBundleDependent: true,
    bulkCompDetected: true,
    isConsumable: true
  },
  collectibleToy: {
    ...base,
    title: "Transformers Age of the Primes Sideways Deluxe Class",
    brand: "Hasbro",
    category: "action figure",
    costBasis: 15,
    averageSoldPrice: 38,
    netProfit: 12.2,
    roi: 81,
    trustedSoldCount: 4,
    soldCount90d: 1,
    activeCount: 5,
    activeListingCount: 5,
    soldListingCount: 4,
    sellThroughRate: 0.18,
    sellThroughRatio: 0.18,
    saturationRatio: 1.25,
    confidenceScore: 74,
    titleMatchScore: 0.68,
    visualMatchScore: 0.74,
    isCollectible: true,
    raritySignal: true
  },
  vintageMedia: {
    ...base,
    title: "Vintage out of print DVD",
    category: "media",
    costBasis: 2,
    averageSoldPrice: 22,
    netProfit: 10,
    roi: 500,
    trustedSoldCount: 3,
    activeCount: 4,
    activeListingCount: 4,
    soldListingCount: 3,
    saturationRatio: 1.33,
    confidenceScore: 68,
    titleMatchScore: 0.62,
    isCollectible: true,
    raritySignal: true
  },
  electronicsAccessory: {
    ...base,
    title: "Generic USB-C charging cable",
    category: "electronics accessory",
    costBasis: 6,
    averageSoldPrice: 12,
    netProfit: -1,
    roi: -16,
    trustedSoldCount: 8,
    activeCount: 300,
    activeListingCount: 300,
    soldListingCount: 8,
    saturationRatio: 37.5,
    confidenceScore: 76,
    titleMatchScore: 0.55,
    returnRisk: true,
    incompleteListingRisk: true
  },
  fakeBundleInflation: {
    ...base,
    title: "Single snack item matching bundle comps",
    category: "grocery",
    costBasis: 1.25,
    averageSoldPrice: 23,
    netProfit: 12,
    roi: 960,
    trustedSoldCount: 3,
    activeCount: 40,
    activeListingCount: 40,
    soldListingCount: 3,
    saturationRatio: 13.33,
    confidenceScore: 60,
    isBundleDependent: true,
    bulkCompDetected: true,
    isConsumable: true
  },
  longTailNicheCollectible: {
    ...base,
    title: "Niche collectible figure variant",
    category: "collectible toy",
    costBasis: 10,
    averageSoldPrice: 45,
    netProfit: 21,
    roi: 210,
    trustedSoldCount: 2,
    activeCount: 1,
    activeListingCount: 1,
    soldListingCount: 2,
    saturationRatio: 0.5,
    confidenceScore: 70,
    titleMatchScore: 0.6,
    visualMatchScore: 0.7,
    isCollectible: true,
    raritySignal: true
  }
};
